### ISSUE TITLE
INVALID CODE REVIEW

### ISSUE THREAD

**Issue by carlos-ssh** [redwing555/Hello-Microverse#2]
**Kindly follow the steps requested in your general information it's needed to have a pull request created.**
![Screen Shot 2021-08-10 at 06 13 14](https://user-images.githubusercontent.com/22258274/128857220-b337b574-be26-47f9-85bf-9dd08f0dd245.png)

**Comment by redwing555** [comment]
Hello, I don't know exactly what went wrong with my project because I followed every step of the top requirements, can you please specify what should be changed in order to pass the code review?
